app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/anny
    username: postgres
    password: mymac
    pool-size: 30
    initialize: true
    driver-class-name: org.postgresql.Driver



#    driver-class-name: org.postgresql.Driver
#    testWhileIdle: true
#    validationQuery: SELECT 1
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create
#      show-sql: true
#  sql:
#    init:
#      mode: ALWAYS
#      continue-on-error: true
